# Generated by Django 3.1.7 on 2021-03-13 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_tutorial_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curriculumitem',
            name='curriculum',
        ),
        migrations.AddField(
            model_name='curriculum',
            name='tutorial',
            field=models.ManyToManyField(to='cart.CurriculumItem'),
        ),
        migrations.AddField(
            model_name='curriculumitem',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cart.customer'),
        ),
        migrations.AlterField(
            model_name='curriculum',
            name='curriculum_id',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='curriculum',
            name='goal',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='curriculum',
            name='topic',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
